var GAME_LEVELS = [                                      
 ["                                                                                                                                                                            ",
  "        xxxxx  xxxxx  x      x      xxxxx  xxxxx  xxxxx        xxxxx   x   x  xxxxx        xxxxx  xxxxx  xxxxx  xxxxx       xxxxx  x   x  xxxxx  xxxxx  xxxx   xxxxx        ",  
  "        x      x   x  x      x      x      x        x            x     x   x  x            x        x    x   x  x   x       x      x   x  x   x  x   x  x   x  x            ",
  "        x      x   x  x      x      xxx    x        x            x     xxxxx  xxx          xxxxx    x    xxxxx  xxxx        xxxxx  xxxxx  xxxxx  xxxx   x   x  xxxxx        ",
  "        x      x   x  x      x      x      x        x            x     x   x  x                x    x    x   x  x   x           x  x   x  x   x  x   x  x   x      x        ",
  "        xxxxx  xxxxx  xxxxx  xxxxx  xxxxx  xxxxx    x            x     x   x  xxxxx        xxxxx    x    x   x  x   x       xxxxx  x   x  x   x  x   x  xxxx   xxxxx        ",
  "                       o                                                                                                                                                    ",
  "                                                                                                                                                                            ",
  "x                                                                                                                                                                           x",
  "x                                  o    o     o                                                                                                                             x",
  "x    @                                                     o o o          o o o                            o o o            o         o         o                       o   x",
  "x                                                                                                                                                                           x",
  "xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxx     xxxxx     xxxxx     xxxxxxxxxxxxxxxxxxxxx",
  "xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxx     xxxxx     xxxxx     xxxxxxxxxxxxxxxxxxxxx"],
  
 
["                                                                                                                                                      ",
  "                                                                                                                                                      ",
  "                                                                                                                                                      ",
  "                                                                                   o o o                                                              ",
  "                                                                      xxx>      =                 <x                                                  ",
  "                                               xxx>      =       <x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxx                                           ",  
  "                                            o  xxxxxxxxxxxxxxxxxxxx                                                                                   ",
  "                                                                                                                                                      ",
  "                                      xxxxxxxx                                                                                                        ",
  "                                   o                                                        xxxxxxxxxxxxxxx                                           ",
  "                                                                                                                                                      ",
  "                                xxxxxxxx                             x       =          x                                                             ",
  "                                                                     xxxxxxxxxxxxxxxxxxxx                                                             ",
  "                             o                                                                        xxxxxxxx    xxx                                 ",
  "                          xxxxxxxx                                                                    x        o    x                                 ",
  "                                                                                                      x             x                                 ",
  "                                                                                                      xxxxxxxxxxx                                     ",
  "            x    o   xxxxxx                                                                           x           o                                   ",
  "            x            <x                                                                           x                                               ",
  "            x            <x                                                                           x      =      x                                 ",
  "            xxxxxx       <x                                                                           xxxxxxxxxxxxxxx                                 ",
  "            x>           <x                                                                                                                           ",
  "            x> o         <x                                                                                                                           ",
  "            x>           <x                                                                                               xxxxxxxxx                   ",
  "            xxxxxxx      <x                                                                           xxxxxxxxxxxxxxxx                        xxxxxxxx",
  "                         <x                                                                 xxxxxxx                                                   ",
  "                      xxxxx                                                            xxxx                                                    o o o x",
  "                          x                                                                                                                           ",
  "  @         x       =     x                                                      xxxxxx                                                              ",
  "            xxxxxxxxxxxxxxx                                                                                                o    o                    x",
  "xxxxxxxxx                                                   xxxxxxx                                                       xxxxxxxxx    xxx    xxxxxxxx",
  "!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!xx!!!!xxx!!!!xxxxxxxxxxxxxxxxxxx!!!!!!xxxxx!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  
  ["                              v   v   v   v   v   v                                                                                                  ",
  "                                                                                                                                                      ",
  "                                                                                                                                                      ",
  "                                                                                                                                                      ",  
  "                                                                                                                                                      ",
  "   @            o                                                                                                                                     ",  
  "                                 o   o   o   o   o                                   x=     x                                                       ",
  "xxxxxxxxxxxxxxxxxxx^^^x                                xxx^^^^xxx^^^^xxxxxxxxxxx     xxxxxxxx                                                         ",
  "                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                            ",
  "                                                                                                                                                      ",
  "                                                                                                                                                      ",
  "                                                                                                                xxxxxxxxxxxxxx     xxxxxxxxx          ",
  "                                                                                                   o o                                                ",
  "                                      o  o  o                                                xxxxxxxxxxxxxx                                           ",
  "          xxxxxxxxxxx            xxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                 ",
  "                                                                                                                                                      ",
  "                                                                                         xxxx                                                         ",
  "                                                                                                                                                      ",
  "                          xxxxxxxx!!!!xxxxx!!!!xxxxxxxx    xxxxxxxxxxx^^^^xxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                ",
  "                          xxx!!!!!!!!!!!!!!!!!!!!!!!xxx                                  xxx!!!!!!!!!!!!!!!!!!!!!!!xxx                                ",
  "                          xxx!!!!!!!!!!!!!!!!!!!!!!!xxx                                  xxx!!!!!!!!!!!!!!!!!!!!!!!xxx                                ",
  "                          xxx!!!!!!!!!!!!!!!!!!!!!!!xxx                                  xxx!!!!!!!!!!!!!!!!!!!!!!!xxx                                ",
  "                          xxxxxxxxxxxxx!v!xxxxxxxxxxxxx                                  xxxxxxxxxxxxx!v!xxxxxxxxxxxxx   v     v     v                ",
  "                                                                                                                                                      ",
  "                                                                                                                                                      ",
  "                 o  o                                                                                                                                  ",
  "               xxxxxxxx            o         o                                                         o                                              ",
  "                          xxxxxxxxxxxxxxxxxxxxxxxx                                                                                                    ",
  "                                                      o      o                                       xxxxxx                                           ",
  "                                                   xxxxxxxxxxxxxxxxx             o o o o o      xxxx        xxxx                                      ",
  "                                                                      xxx                                                                             ",
  "                                                                           xxxxxxxxxxxxxxxxxxxxx                                                      ",
  "                                                                                                                   x      =                  x         ",
  "                                                                                                                   xxxxxxxxxxxxxxxxxxxxxxxxxxx     o ",
  "                                                                                                                                                  xxxx"],
  
  
 ["                                                                  v                                        vvvv    vvvv    vvvv                  o    ",
  "                                                                                                                                               xxxx   ",
  "                                                                                                                                       xxxx           ",
  "                                                                                                      xxxxx    xxxx    xxxx    xxxx                   ",
  "                                                                                   xxxxxxxx      xxx                                                  ",  
  "                                                                                     o  o         <x                                                  ",
  "                                                           o         o      x          =          <x                                                  ",
  "                                                                            xxxxxxxxxxxxxxxxxxxxxxxx                                                  ",
  "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                         ",
  "        xxxxxxxxxxxxxxx       xxxxxx      xxxxx                                                                                                       ",
  "        >                                                                                                                                             ",
  "        >              o o o                                                                                                                          ",
  "        >                                                                                                                                             ",
  "        >       xxxxxxxxxxxxxxxxxxxx                                                                                                                  ",
  "        >                          <                                                                                                                  ",
  "        x> o                    =  x                                                                                                                  ",  
  "        xxxx^^^^xxxx^^^^xxxx^^^^xxxx                                                                                                                  ",
  "                                    xx                                                                                                                ",
  "                                    xx            =         xx                                                                                        ",
  "                                    xxxxxxxxxxxxxxxxxxxxxxxxxx   xx   xxxxxxxxxxxx  xxxx  xxxxxxxxxxxxxxxx     xxxxxxxxx      xxx      ooo            ",
  "                                                                                                                                                      ",
  "                                                                 o                                                                                    ",
  "                                                                                                                                      xxxxx           ",
  "                                                                                                                                                      ",
  "                                                          xxxxxvvvvxxxxx                                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxx            ",
  "                             xxxxxxxxxxxxxxxxxxxvvv                            vvvxxxxxxxxxxxxxxxxxxxxxxxxxx                                          ",
  "                                                   xxxx                    xxxx                                                                       ",
  "                   xxxxxxx                                                                                                                            ",
  "          xxx            x                                                                                                                            ",
  "          <x>            x                                                                                                                            ",
  " @    xxxxxxxxxxxxxxxxxxxx                                                                                                                            ",
  "                                                                                                                                                      ",
  "xxx                                                                                                                                                   ",
  "                                                                                                                                                      ",
  "                                                                                                                                                      ",
  "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"]
  
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
